# Generated by Django 4.2.9 on 2024-09-16 11:08

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_external_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='events')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('category', models.CharField(choices=[('RALLY', 'Rally'), ('HILL-CLIMB', 'Hill Climb'), ('AUTO-CROSS', 'Auto Cross'), ('KARTING', 'Karting')], max_length=16)),
                ('provider_name', models.CharField(choices=[('KRONOLIVE', 'Kronolive'), ('KRONOBOT', 'Kronobot')], default='KRONOBOT', max_length=16)),
            ],
        ),
    ]
