# Generated by Django 4.2.9 on 2024-09-18 11:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_external_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='events')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('RALLY', 'Rally'), ('HILL-CLIMB', 'Hill Climb'), ('AUTO-CROSS', 'Auto Cross'), ('KARTING', 'Karting')], max_length=16)),
                ('provider_name', models.CharField(choices=[('KRONOLIVE', 'Kronolive'), ('KRONOBOT', 'Kronobot')], default='KRONOBOT', max_length=16)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('car', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('dorsal', models.CharField(max_length=12)),
                ('copilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscription_copilot', to='events.competitor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_event', to='events.event')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_pilot', to='events.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_time', models.DurationField()),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.inscription')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.section')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='events.event'),
        ),
    ]
