# Generated by Django 4.2.9 on 2024-09-17 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('car', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('dorsal', models.CharField(max_length=12)),
                ('copilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscription_copilot', to='events.competitor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_event', to='events.event')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_pilot', to='events.competitor')),
            ],
        ),
    ]
