# Generated by Django 4.2.9 on 2024-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_competitor_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
