# Generated by Django 4.2.9 on 2024-09-17 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_provider_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_time', models.DurationField()),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.inscription')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.section')),
            ],
        ),
    ]
